In [17]:
import gymnasium as gym
import ale_py
import ViTDQN

import DQN
import ReplayBuffer
import Agent


import numpy as np
from collections import deque
import random
from random import sample
import torch
import tensorflow as tf
import os

gym.register_envs(ale_py)
env = gym.make("ALE/Pong-v5",obs_type='rgb', render_mode='rgb_array', full_action_space = False)

In [15]:
print(env.action_space.n)

6


In [12]:
env_reset = env.reset()
print(env_reset)
print(len(env_reset))
x = env.step(0)
print(len(x))


(array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [109, 118,  43],
        [109, 118,  43],
        [109, 118,  43]],

       [[109, 118,  43],
        [109, 118,  43],
        [109, 118,  43],
        ...,
        [109, 118,  43],
        [109, 118,  43],
        [109, 118,  43]],

       [[109, 118,  43],
        [109, 118,  43],
        [109, 118,  43],
        ...,
        [109, 118,  43],
        [109, 118,  43],
        [109, 118,  43]],

       ...,

       [[ 53,  95,  24],
        [ 53,  95,  24],
        [ 53,  95,  24],
        ...,
        [ 53,  95,  24],
        [ 53,  95,  24],
        [ 53,  95,  24]],

       [[ 53,  95,  24],
        [ 53,  95,  24],
        [ 53,  95,  24],
        ...,
        [ 53,  95,  24],
        [ 53,  95,  24],
        [ 53,  95,  24]],

       [[ 53,  95,  24],
        [ 53,  95,  24],
        [ 53,  95,  24],
        ...,
        [ 53,  95,  24],
        [ 53,  95,  24],
        [ 53,  95,  24]

In [11]:
layer01 = env_reset[0]
print(layer01)
print(type(layer01))
layer01_mean = np.mean(layer01, axis=-1)

print(len(layer01_mean))

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 ...

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ...
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ...
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ...
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]]
<class 'numpy.ndarray'>
210


In [6]:
layer02 = env_reset[0][0]
print(len(layer02))

160


In [7]:
layer03 = env_reset[0][0][0]
print(len(layer03))

3


In [8]:
import functions as f

state = f.preprocess_observation(layer01)
print(type(state))
print(len(state))

Completed preprocessing. Final shape: (1, 64, 64, 3)
<class 'torch.Tensor'>
1


In [9]:
image = tf.random.uniform(shape=(210, 160, 3), minval=0, maxval=255, dtype=tf.float32)

print(len(image))
print(image[0])


210
tf.Tensor(
[[232.10696     92.23619    110.189835  ]
 [237.66187     26.254099   160.66988   ]
 [118.95414    119.25076    105.99422   ]
 [195.7644      78.49503    232.89734   ]
 [209.80623     16.15561    119.32083   ]
 [159.6501      69.96826     36.185883  ]
 [ 68.53558    142.95198     88.271515  ]
 [103.29494    140.32462    156.26907   ]
 [ 13.512591   118.169525    60.067146  ]
 [112.99469    208.10005     73.058464  ]
 [ 94.617966   111.782524   108.19068   ]
 [214.65324    223.53447    163.19742   ]
 [ 55.228973    48.135696    66.27392   ]
 [ 67.422516   170.49551    200.45804   ]
 [ 30.438282   252.14607    149.3077    ]
 [177.49814    149.21547    142.03914   ]
 [ 98.60398      6.963111   232.00543   ]
 [105.92746     98.07508    214.92252   ]
 [ 46.06599    134.76631    203.47807   ]
 [ 38.40831     81.114914    31.005302  ]
 [160.8392      93.55712    137.48949   ]
 [183.41992     93.379196   211.5512    ]
 [ 92.231964   154.81892     34.614655  ]
 [109.298584   138.

In [ ]:
env = gym.make("ALE-P)