In [2]:
import gymnasium as gym
import ale_py
import ViTDQN

import DQN
import ReplayBuffer
import Agent


import numpy as np
from collections import deque
import random
from random import sample
import torch
import tensorflow as tf

gym.register_envs(ale_py)
env = gym.make("ALE/Pong-v5", render_mode='rgb_array')

/Users/nickocruz/Desktop/RL-Final Project/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
A.L.E: Arcade Learning Environment (version 0.10.1+6a7e0ae)
[Powered by Stella]


In [10]:
env_reset = env.reset()
print(len(env_reset))
x = env.step(0)
print(len(x))


2
5


In [11]:
layer01 = env_reset[0]
print(len(layer01))
print(type(layer01))
layer01_mean = np.mean(layer01, axis=-1)

print(len(layer01_mean))

210
<class 'numpy.ndarray'>
210


In [12]:
layer02 = env_reset[0][0]
print(len(layer02))

160


In [13]:
layer03 = env_reset[0][0][0]
print(len(layer03))

3


In [14]:
import functions as f

state = f.preprocess_observation(layer01)
print(type(state))
print(len(state))

<class 'numpy.ndarray'>
16


In [15]:
image = tf.random.uniform(shape=(210, 160, 3), minval=0, maxval=255, dtype=tf.float32)

print(len(image))
print(image[0])


210
tf.Tensor(
[[1.79373718e+02 1.65522003e+02 4.69184532e+01]
 [1.57124664e+02 2.07637390e+02 1.73071320e+02]
 [4.90486488e+01 1.81032471e+02 2.34344879e+02]
 [1.62341614e+02 9.13199234e+01 1.77376007e+02]
 [7.75713196e+01 2.06994751e+02 1.23456200e+02]
 [9.53038406e+01 2.00621964e+02 7.45063705e+01]
 [1.54344345e+02 1.26371490e+02 1.14760101e+02]
 [2.04717789e+02 3.99847679e+01 1.85320007e+02]
 [1.87558365e+02 2.30005280e+02 1.28004364e+02]
 [5.31672935e+01 8.74271393e+01 2.42234909e+02]
 [1.69940781e+02 6.34288712e+01 1.36760284e+02]
 [1.58410675e+02 5.21415024e+01 1.95595657e+02]
 [9.26928635e+01 1.50733017e+02 2.40021515e+02]
 [5.22169189e+01 2.04706848e+02 1.59082382e+02]
 [1.14775909e+02 1.27703547e-01 4.11531601e+01]
 [1.08554520e+02 5.54577217e+01 2.06695862e+02]
 [7.69180298e+01 2.20316345e+02 2.14773041e+02]
 [1.22468643e+01 1.17791252e+01 1.71148926e+02]
 [4.85230637e+01 2.46529560e+01 1.14829838e+00]
 [8.28138199e+01 8.83653259e+01 2.15366943e+02]
 [1.01450241e+02 1.876920